
title: Franziska Conzen-Nehb
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/conzen-nehb-static" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
sass:
  sass_dir: _sass
include: 
  - '_pages'
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
navigation:
  - title: Home
    url: /
  - title: Über mich
    url: /ueber_mich
  - title: Leistungen
    url: /leistungen
  - title: Kontakt
    url: /kontakt
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']