
title: Franziska Conzen-Nehb Praxis für Krankengymnastik
email:
description:  # this means to ignore newlines until "baseurl:"
  "Herzlich Willkommen in der Praxis für Krankengymnastik, Franziska Conzen-Nehb.
  Krankengymnastische Behandlungen | Chirurgische, orthopädische, neurologische Nachbehandlungen | Behandlungen nach Bobath Konzept - PNF | Manuelle Therapie | Manuelle Lymphdrainage
Gerätegestützte Krankengymnastik"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://praxisfranziskaconzen-nehb.de/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
sass:
  sass_dir: _sass
include:
  - '_pages'
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
navigation:
  - title: Home
    url: /
  - title: Über mich
    url: ueber_mich.html
  - title: Leistungen
    url: leistungen.html
  - title: Kontakt
    url: kontakt.html
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']